# Generated by Django 4.0.1 on 2022-03-31 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cname',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sname',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='tname',
            new_name='teacher_name',
        ),
    ]
